//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLEON code	GLEON control vocab	Recommended units	Alternative units
        ///BaroP	Barometric_Pressure	hPa	mmHg,mbar,kPa
        ///BFrq	Bouyancy_Frequency
        ///CDOM	Colored_Dissolved_Organic Matter	ug/L
        ///CDOMCR	Colored_Dissolved_Organic Matter_Coefficient_of_Range
        ///Chl	Chlorophyll a	ug/L
        ///ChlF	Chlorophyll_Fluorescence	RFU	RFUB,ug/L chl
        ///Cl	Chloride	mg/m^3	g/m^3,ppm,ppb
        ///CO2A	Atmospheric_Carbon_Dioxide	ppm
        ///Cond	Conductivity	mS/cm	uS/cm
        ///CondSp	Specific_Conductance	mS/cm	uS/cm
        ///Depth	Depth	m	ft
        ///DIN	Dissolved_Inorganic_Nitrogen
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABBREVIATIONS {
            get {
                return ResourceManager.GetString("ABBREVIATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF	AFGHANISTAN	+04:30
        ///AL	ALBANIA	+01
        ///DZ	ALGERIA	+01
        ///AS	AMERICAN SAMOA	-11				
        ///AD	ANDORRA	+01		
        ///AO	ANGOLA	+01
        ///AI	ANGUILLA	-04
        ///AQ	ANTARCTICA	-04	+03	+05	+07	+08	+10	+12
        ///AG	ANTIGUA AND BARBUDA	-04
        ///AR	ARGENTINA	-03	
        ///AM	ARMENIA	+04
        ///AW	ARUBA	-04						
        ///AU	AUSTRALIA	+08	+9:30	+10				
        ///AT	AUSTRIA	+01						
        ///AZ	AZERBAIJAN							
        ///BS	BAHAMAS							
        ///BH	BAHRAIN							
        ///BD	BANGLADESH							
        ///BB	BARBADOS							
        ///BY	BELARUS							
        ///BE	BELGIUM							
        ///BZ	BELIZE							
        ///BJ	BENIN							
        ///BM	BERMUDA							
        ///BT	BHU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COUNTRY_CODE {
            get {
                return ResourceManager.GetString("COUNTRY_CODE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Loading_video {
            get {
                object obj = ResourceManager.GetObject("Loading_video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
